// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: captura.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "captura.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* Captura_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Captura_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_captura_2eproto() {
  protobuf_AddDesc_captura_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "captura.proto");
  GOOGLE_CHECK(file != NULL);
  Captura_descriptor_ = file->message_type(0);
  static const int Captura_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Captura, usuario_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Captura, timestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Captura, imagen_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Captura, dispositivo_),
  };
  Captura_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Captura_descriptor_,
      Captura::default_instance_,
      Captura_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Captura, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Captura, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Captura));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_captura_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Captura_descriptor_, &Captura::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_captura_2eproto() {
  delete Captura::default_instance_;
  delete Captura_reflection_;
}

void protobuf_AddDesc_captura_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rcaptura.proto\"R\n\007Captura\022\017\n\007usuario\030\001 "
    "\002(\t\022\021\n\ttimestamp\030\002 \002(\004\022\016\n\006imagen\030\003 \002(\014\022\023"
    "\n\013dispositivo\030\004 \001(\t", 99);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "captura.proto", &protobuf_RegisterTypes);
  Captura::default_instance_ = new Captura();
  Captura::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_captura_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_captura_2eproto {
  StaticDescriptorInitializer_captura_2eproto() {
    protobuf_AddDesc_captura_2eproto();
  }
} static_descriptor_initializer_captura_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Captura::kUsuarioFieldNumber;
const int Captura::kTimestampFieldNumber;
const int Captura::kImagenFieldNumber;
const int Captura::kDispositivoFieldNumber;
#endif  // !_MSC_VER

Captura::Captura()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Captura::InitAsDefaultInstance() {
}

Captura::Captura(const Captura& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Captura::SharedCtor() {
  _cached_size_ = 0;
  usuario_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  timestamp_ = GOOGLE_ULONGLONG(0);
  imagen_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  dispositivo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Captura::~Captura() {
  SharedDtor();
}

void Captura::SharedDtor() {
  if (usuario_ != &::google::protobuf::internal::kEmptyString) {
    delete usuario_;
  }
  if (imagen_ != &::google::protobuf::internal::kEmptyString) {
    delete imagen_;
  }
  if (dispositivo_ != &::google::protobuf::internal::kEmptyString) {
    delete dispositivo_;
  }
  if (this != default_instance_) {
  }
}

void Captura::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Captura::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Captura_descriptor_;
}

const Captura& Captura::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_captura_2eproto();
  return *default_instance_;
}

Captura* Captura::default_instance_ = NULL;

Captura* Captura::New() const {
  return new Captura;
}

void Captura::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_usuario()) {
      if (usuario_ != &::google::protobuf::internal::kEmptyString) {
        usuario_->clear();
      }
    }
    timestamp_ = GOOGLE_ULONGLONG(0);
    if (has_imagen()) {
      if (imagen_ != &::google::protobuf::internal::kEmptyString) {
        imagen_->clear();
      }
    }
    if (has_dispositivo()) {
      if (dispositivo_ != &::google::protobuf::internal::kEmptyString) {
        dispositivo_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Captura::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string usuario = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_usuario()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->usuario().data(), this->usuario().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_timestamp;
        break;
      }

      // required uint64 timestamp = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_timestamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &timestamp_)));
          set_has_timestamp();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_imagen;
        break;
      }

      // required bytes imagen = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_imagen:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_imagen()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_dispositivo;
        break;
      }

      // optional string dispositivo = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_dispositivo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_dispositivo()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->dispositivo().data(), this->dispositivo().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Captura::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string usuario = 1;
  if (has_usuario()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->usuario().data(), this->usuario().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->usuario(), output);
  }

  // required uint64 timestamp = 2;
  if (has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->timestamp(), output);
  }

  // required bytes imagen = 3;
  if (has_imagen()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      3, this->imagen(), output);
  }

  // optional string dispositivo = 4;
  if (has_dispositivo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->dispositivo().data(), this->dispositivo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->dispositivo(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Captura::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string usuario = 1;
  if (has_usuario()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->usuario().data(), this->usuario().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->usuario(), target);
  }

  // required uint64 timestamp = 2;
  if (has_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->timestamp(), target);
  }

  // required bytes imagen = 3;
  if (has_imagen()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->imagen(), target);
  }

  // optional string dispositivo = 4;
  if (has_dispositivo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->dispositivo().data(), this->dispositivo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->dispositivo(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Captura::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string usuario = 1;
    if (has_usuario()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->usuario());
    }

    // required uint64 timestamp = 2;
    if (has_timestamp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->timestamp());
    }

    // required bytes imagen = 3;
    if (has_imagen()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->imagen());
    }

    // optional string dispositivo = 4;
    if (has_dispositivo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->dispositivo());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Captura::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Captura* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Captura*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Captura::MergeFrom(const Captura& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_usuario()) {
      set_usuario(from.usuario());
    }
    if (from.has_timestamp()) {
      set_timestamp(from.timestamp());
    }
    if (from.has_imagen()) {
      set_imagen(from.imagen());
    }
    if (from.has_dispositivo()) {
      set_dispositivo(from.dispositivo());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Captura::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Captura::CopyFrom(const Captura& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Captura::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void Captura::Swap(Captura* other) {
  if (other != this) {
    std::swap(usuario_, other->usuario_);
    std::swap(timestamp_, other->timestamp_);
    std::swap(imagen_, other->imagen_);
    std::swap(dispositivo_, other->dispositivo_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Captura::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Captura_descriptor_;
  metadata.reflection = Captura_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
